
import React, { useEffect, useRef, useState } from 'react';

interface MermaidBlockProps {
  code: string;
}

export const MermaidBlock: React.FC<MermaidBlockProps> = ({ code }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<boolean>(false);

  // Helper to fix common Mermaid syntax errors generated by LLMs
  const sanitizeMermaidCode = (rawCode: string): string => {
    let sanitized = rawCode.trim();

    // 1. Fix Markdown List Numbering (e.g., "1. A-->B" -> "A-->B")
    sanitized = sanitized.replace(/^\s*\d+[\.)]\s+/gm, '');
    
    // 2. Fix Missing Newlines between distinct statements
    // Detects pattern where a node definition is immediately followed by another on the same line
    // e.g., "A[Label] B[Label]" -> "A[Label]\nB[Label]"
    // e.g., "A-->B C-->D" -> "A-->B\nC-->D"
    sanitized = sanitized.replace(/([\]\)])\s+([a-zA-Z0-9_]+[\[\(])/g, '$1\n$2');
    sanitized = sanitized.replace(/([a-zA-Z0-9_"])\s+([a-zA-Z0-9_]+(\s*-->|\s*-\.->|\s*==>))/g, '$1\n$2');

    // 3. Fix Comma Separated Targets (e.g., "A --> B, C") -> "A --> B & C"
    // This works for standard flowcharts.
    sanitized = sanitized.replace(/(-->|-.->|==>)\s*([a-zA-Z0-9_]+)((?:,\s*[a-zA-Z0-9_]+)+)/g, (match, arrow, first, rest) => {
        const replacement = rest.replace(/,/g, ' &');
        return `${arrow} ${first}${replacement}`;
    });

    // 4. Fix Unquoted Special Characters in Labels
    // Aggressively looks for labels [ ... ] that contain ( ) or [ ] but aren't quoted
    sanitized = sanitized.replace(/([a-zA-Z0-9_]+)\[(?!")([^\]]*?[=\(\)\[\]][^\]]*?)\]/g, (match, id, content) => {
        // Replace internal brackets/parens with safe alternatives if not quoted
        const safeContent = content.replace(/\[/g, '(').replace(/\]/g, ')').replace(/"/g, "'");
        return `${id}["${safeContent}"]`;
    });

    // 5. Ensure Standard Graph Declaration has newline
    const graphTypes = ['graph TD', 'graph LR', 'graph TB', 'graph BT', 'flowchart TD', 'flowchart LR', 'mindmap'];
    for (const type of graphTypes) {
        // If code starts with type but no newline immediately after
        if (sanitized.startsWith(type) && !sanitized.startsWith(type + '\n') && !sanitized.startsWith(type + '\r')) {
             sanitized = type + '\n' + sanitized.substring(type.length);
        }
    }
    
    // 6. Handle 'end' keyword misuse
    // If 'end' is used as an ID, replace it.
    sanitized = sanitized.replace(/(\s-->\s*|\s-.->\s*|\s==>\s*)end(\s|;|\[|\(|$)/gm, '$1node_end$2');
    sanitized = sanitized.replace(/(^|\s)end([\[\(])/gm, '$1node_end$2');

    return sanitized;
  };

  useEffect(() => {
    const renderDiagram = async () => {
      if (!code || !(window as any).mermaid) return;

      try {
        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;
        const safeCode = sanitizeMermaidCode(code);
        
        const { svg } = await (window as any).mermaid.render(id, safeCode);
        setSvg(svg);
        setError(false);
      } catch (err) {
        console.error('Mermaid render error:', err);
        setError(true);
      }
    };

    renderDiagram();
  }, [code]);

  if (error) return (
    <div className="p-4 border border-red-500/20 bg-red-500/5 rounded-xl text-center overflow-hidden">
        <p className="text-xs text-red-400 font-mono mb-2">Diagram Visualization Failed</p>
        <p className="text-[10px] text-gray-500 font-mono break-all opacity-50">{code.substring(0, 100)}...</p>
    </div>
  );
  
  if (!svg) return (
      <div className="w-full h-32 rounded-xl bg-white/5 animate-pulse flex items-center justify-center">
          <span className="text-xs text-gray-500">Rendering Diagram...</span>
      </div>
  );

  return (
    <div 
      ref={containerRef}
      className="mermaid-diagram w-full overflow-x-auto flex justify-center bg-white/5 p-4 rounded-xl border border-white/10 my-4 shadow-inner"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
};
